using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;

namespace _24hr_Game_Challenge
{
    public partial class Map : Form
    {


       bool right, left;
       XmlDocument xmlDoc = new XmlDocument(); // Create an XML document object

        //bool jump;

        public Map()
        {
            InitializeComponent();
        }

        private void enumerateMaps(object sender, EventArgs e)
        {
            foreach (string file in Directory.EnumerateFiles("maps", "*.xml"))
            {
                string contents = File.ReadAllText(file);

                string createText = "Automatically generated by 24hr game challenge" + Environment.NewLine;
                File.WriteAllText("maps", createText);

                // Open the file to read from.
                string readText = File.ReadAllText("maps");
            }
        }

        private void timer1_Tick(object sender, EventArgs e)
        {

            if (right == true) {player1.Left += 5; }
            if (left == true) { player1.Left -= 5; }
        }

      

        private void Map_KeyDown(object sender, KeyEventArgs e)
        {
            if(e.KeyCode == Keys.Right || e.KeyCode == Keys.D) { right = true; }
            if(e.KeyCode == Keys.Left || e.KeyCode == Keys.A) { left = true; }
           
        }

        private void Form1_Load(object sender, EventArgs e)
        {
        }

        private void screen_Paint(object sender, PaintEventArgs e)
        {

        }

        private void Map_KeyUp(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Right || e.KeyCode == Keys.D) { right = false; }
            if (e.KeyCode == Keys.Left || e.KeyCode == Keys.A) { left = false; }
        }



    }
}
